### ISSUE TITLE
Why the last 1000 conversations?

### ISSUE THREAD

**Issue by douglasg14b** [Bentlybro/GPTSearch#1]
Just curious. Is this limitation imposed by the ChatGPT API or?

**Comment by Bentlybro** [comment]
i simply set the limit to be 1000, it loads 100 conversations each API call, (they limit it to 100 conversations per call), so you are doing 10 api calls in a short time, so i added the limit it to try not get rate limited, you can always change the limit to be more if you want to by changing https://github.com/Bentlybro/GPTSearch/blob/91aee2aa6416f689722961976b78d7f3eed5b2e9/GPTSearch%20-%20Firefox/background.js#L8
